sudo: required
services:
  - docker

before_install:
  - docker build -t liyakat/webapp -f Dockerfile.dev .

script:
  - docker run liyakat/webapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "fragun"
  env: "Fragun-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-284947593819"
  bucket_path: "fragun"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
